config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Defines the root path route ("/")
  root 'access#menu'
  get 'about', to: 'main#about'
  get 'hello', to: 'main#hello'
  get 'main/index' # match 'main/index', to: 'main#index', via: :get

  # Session routes
  get 'menu' => 'access#menu'
  get 'login' => 'access#new'
  delete 'logout' => 'access#destroy'
  resource :access, controller: 'access', only: %i[new create destroy] do
    member do
      get :menu
    end
  end

  # Categories routes
  resources :categories do
    member do
      get :delete
    end
  end
  # get 'categories/index'
  # get 'categories/show'
  # get 'categories/new'
  # get 'categories/edit'
  # get 'categories/delete'

  # Tasks routes
  resources :tasks do
    member do
      get :delete
    end
  end
  # get 'tasks/index'
  # get 'tasks/new'
  # get 'tasks/edit'
  # get 'tasks/show'
  # get 'tasks/delete'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/application_record.rb
# frozen_string_literal: true

# /app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :tasks, dependent: :restrict_with_error

  def related_tasks
    return '-' if tasks.empty?

    tasks.map(&:name).join(', ')
  end
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :category, optional: true
end

app/controllers/access_controller.rb
# frozen_string_literal: true

class AccessController < ApplicationController
  layout 'application'

  skip_before_action :confirm_logged_in, only: %i[new create]

  # display menu
  def menu; end

  # display login form
  def new
    redirect_to menu_path if logged_in?
  end

  # processs login form
  def create
    logger.info("*** Login User #{params[:username]}")
    # do login process here
    cookies[:username] = params[:username]
    session[:user_id] = 1234
    flash[:notice] = I18n.t 'login_success'
    redirect_to(menu_path)
  end

  # logout user
  def destroy
    logger.info("*** Logged out User #{cookies[:username]}")
    # do logout process here
    session[:user_id] = nil
    cookies[:username] = nil
    flash[:notice] = I18n.t 'logout_success'
    redirect_to(login_path)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :user_info_from_session
  before_action :confirm_logged_in

  private

  def user_info_from_session
    @username = cookies[:username]
    @user_id = session[:user_id]
  end

  def logged_in?
    session[:user_id].present?
  end

  def confirm_logged_in
    return false if logged_in?

    flash[:notice] = I18n.t 'ask_login'
    redirect_to login_path
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :find_category, only: %i[show edit update destroy delete]

  def index
    @categories = Category.order(:name)
  end

  def show; end

  def new
    @count = Category.count
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(required_params)
    if @category.save
      redirect_to categories_path
    else
      # The 'new' action is NOT being called here
      # Assign any instance variables needed
      render('new')
    end
  end

  def update
    if @category.update(required_params)
      redirect_to category_path(@category)
    else
      render('edit')
    end
  end

  def delete; end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private

  def find_category
    @category = Category.find(params[:id])
  end

  def required_params
    params.require(:category).permit(:name)
  end
end

app/controllers/main_controller.rb
# frozen_string_literal: true

# /app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    # render 'index'
    render 'access/menu'
  end

  def about
    # render 'about'
    @created_by = 'dicafis'
    @id = params['id']
    @page = params[:page]
  end

  def hello
    redirect_to action: 'index'
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

# /app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: %i[show edit update destroy delete]

  def index
    @tasks = Task.order(:position)
  end

  def show; end

  def new
    @count = Task.count
    @task = Task.new(position: @count + 1)
  end

  def edit; end

  def create
    @task = Task.new(required_params)
    if @task.save
      redirect_to tasks_path
    else
      # The 'new' action is NOT being called here
      # Assign any instance variables needed
      # @count = Task.count + 1
      render('new')
    end
  end

  def update
    if @task.update(required_params)
      redirect_to task_path(@task)
    else
      render('edit')
    end
  end

  def delete; end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def find_task
    @task = Task.find(params[:id])
  end

  def required_params
    params.require(:task).permit(:name, :position, :completed, :description, :category_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# /app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
    render(partial: 'layouts/error_messages', locals: { object: object })
  end

  def status_tag(boolean)
    if boolean
      content_tag(:span, '', class: 'status true')
    else
      content_tag(:span, '', class: 'status false')
    end
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/main_helper.rb
# frozen_string_literal: true

# /app/helpers/main_helper.rb
module MainHelper
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

# /app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/access/menu.html.erb
<%= content_for :title, 'Menu' %>

<div class="access index">
  <h1>Menu</h1>

  <ul>
    <li><%= link_to('Manage Tasks', tasks_path) %></li>
    <li><%= link_to('Manage Categories', categories_path) %></li>
    <li><%= link_to('About', {controller: 'main', action: 'about'}) %></li>
  </ul>

</div>

app/views/access/new.html.erb
<div class="access new">
  <h2>Welcome</h2>
  <p>A simulated log in form</p>

  <%= form_tag(access_path) do %>
    <table summary="login">
      <tr>
        <th><%= label_tag(:username) %></th>
        <td><%= text_field_tag(:username, params[:username]) %></td>
      </tr>
      <tr>
        <th><%= label_tag(:password) %></th>
        <td><%= password_field_tag(:password) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= submit_tag("Log In") %>
    </div>

  <% end %>
</div>

app/views/categories/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Catedory form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
</table>

app/views/categories/delete.html.erb
<%= link_to("Back to List", categories_path, class: 'back-link') %>

<div class="categories delete">
  <h2>Delete Category</h2>

  <%= form_for(@category, method: 'delete') do |f| %>
    <% # url: category_path(@category), method: 'delete' %>

    <p>Are you sure you want to permanently delete this Category?</p>
    <p><%= @category.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Category") %>
    </div>

  <% end %>
</div>

app/views/categories/edit.html.erb
<%= link_to("Back to List", categories_path, :class => 'back-link') %>

<div class="edit new">
  <h2>Edit Category</h2>

  <%= form_for(@category) do |f| %>
    <% # url: categories_path(@task), method: 'patch' %>

    <%= render(partial: 'form', locals: { f: f }) %>

    <div class="form-buttons">
      <%= f.submit("Edit Category") %>
    </div>

  <% end %>
</div>

app/views/categories/index.html.erb
<div class="categories index">
  <h2>Categories</h2>

  <%= link_to("Add New Category", new_category_path, class: 'action new') %>

  <table class="listing" summary="Category list" style="width: 100%;">
    <tr class="header">
      <th>#</th>
      <th>Category</th>
      <th>Tasks related</th>
      <th>Actions</th>
    </tr>
    <% @categories.each do |category| %>
    <tr>
      <td><%= category.id %></td>
      <td><%= category.name %></td>
      <td><%= category.related_tasks %></td>
      <td class="actions">
        <%= link_to("Show", category_path(category), class: 'action show') %>
        <%= link_to("Edit", edit_category_path(category), class: 'action edit') %>
        <%= link_to("Delete", delete_category_path(category), class: 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/categories/new.html.erb
<%= link_to("Back to List", categories_path, :class => 'back-link') %>

<div class="categories new">
  <h2>Create Category</h2>

  <%= form_for(@category) do |f| %>
    <% # url: categories_path, method: 'post' %>

    <%= render(partial: 'form', locals: { f: f }) %>

    <div class="form-buttons">
      <%= f.submit("Create Category") %>
    </div>

  <% end %>
</div>

app/views/categories/show.html.erb
<%= link_to("Back to List", categories_path, class: 'back-link') %>

<div class="categories show">
  <h2>Show Category</h2>

  <div class="actions">
    <%= link_to('Edit', edit_category_path(@category)) %>
    <%= link_to('Delete', delete_category_path(@category)) %>
  </div>

  <table summary="Category detail view">
    <tr>
      <th>Name</th>
      <td><%= @category.name %></td>
    </tr>
    <tr>
      <th>Tasks related</th>
      <td>
        <%= @category.related_tasks %>
      </td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @category.created_at.to_fs(:long) %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @category.updated_at.to_fs(:long) %></td>
    </tr>
  </table>

</div>

app/views/layouts/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
  <div id="error-explanation">
		<h2><%= pluralize(object.errors.size, 'error') %> prohibited this record from being saved</h2>
		<p>There were problems with the following fields:</p>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice].present? %>
  <div id="flash-notice" style="border: 1px solid green; color: green; padding: 10px;">
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager<%= ' - ' + yield(:title) if content_for?(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= yield(:script) %>
  </head>

  <body>
    <header>
      <%= link_to(menu_path) do %>
        <%= image_tag('task_manager_logo.png', height: 25, alt: 'Task Manager Logo') %>
      <% end %>
      <% if session[:user_id].present? %>
        <span>
          User: <%= @username %> | <%= button_to('Logout', logout_path, {method: :delete}) %>
        </span>
      <% end %>
    </header>

    <div id="content">
      <%= render(partial: 'layouts/flash') %>
      <%= yield %>
    </div>

    <footer>
      Copyright <%= Time.now.year %>
    </footer>
  </body>
</html>

app/views/main/about.html.erb
<%= content_for :title, 'About' %>

<h1>Main#about</h1>
<p>Description of the TaskManager</p>
<p>Created by <%= @created_by %></p>

<% content_for(:script) do %>
  <% name = "Peluchosa'); alert('Gotcha" %>
  <%= javascript_tag("alert('Welcome, #{j(name)}!');") %>
<% end %>

app/views/main/index.html.erb
<h1>Task Manager</h1>
<p>This is an application for managing a to do list.</p>

<%= link_to('Categories', categories_path) %><br />
<%= link_to('Tasks', tasks_path) %><br />

<%= link_to 'About', { action: 'about', page: 5, id: 20 } %><br />

app/views/tasks/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Task form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.text_field(:position) %></td>
  </tr>
  <tr>
    <th>Completed</th>
    <td><%= f.check_box(:completed) %></td>
  </tr>
  <tr>
    <th>Description</th>
    <td><%= f.text_area(:description) %></td>
  </tr>
  <tr>
    <th>Category</th>
    <td><%= f.collection_select :category_id, Category.all, :id, :name, include_blank: true %></td>
  </tr>
</table>

app/views/tasks/delete.html.erb
<%= link_to("Back to List", tasks_path, class: 'back-link') %>

<div class="tasks delete">
  <h2>Delete Task</h2>

  <%= form_for(@task, method: 'delete') do |f| %>
    <% # url: task_path(@task), method: 'delete' %>

    <p>Are you sure you want to permanently delete this task?</p>
    <p><%= @task.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Task") %>
    </div>

  <% end %>
</div>

app/views/tasks/edit.html.erb
<%= link_to("Back to List", tasks_path, :class => 'back-link') %>

<div class="edit new">
  <h2>Edit Task</h2>

  <%= form_for(@task) do |f| %>
    <% # url: tasks_path(@task), method: 'patch' %>

    <%= render(partial: 'form', locals: { f: f }) %>

    <div class="form-buttons">
      <%= f.submit("Edit Task") %>
    </div>

  <% end %>
</div>

app/views/tasks/index.html.erb
<div class="tasks index">
  <h2>Tasks</h2>

  <%= link_to("Add New Task", new_task_path, class: 'action new') %>

  <table class="listing" summary="Task list" style="width: 100%;">
    <tr class="header">
      <th>#</th>
      <th>Task</th>
      <th>Completed</th>
      <th>Description</th>
      <th>Category</th>
      <th>Actions</th>
    </tr>
    <% @tasks.each do |task| %>
    <tr>
      <td><%= task.position %></td>
      <td><%= task.name %></td>
      <td><%= status_tag(task.completed?) %></td>
      <td><%= truncate(task.description, length: 30) %></td>
      <td><%= task.category&.name || '-' %></td>
      <td class="actions">
        <%= link_to("Show", task_path(task), class: 'action show') %>
        <%= link_to("Edit", edit_task_path(task), class: 'action edit') %>
        <%= link_to("Delete", delete_task_path(task), class: 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/tasks/new.html.erb
<%= link_to("Back to List", tasks_path, :class => 'back-link') %>

<div class="tasks new">
  <h2>Create Task</h2>

  <%= form_for(@task) do |f| %>
    <% # url: tasks_path, method: 'post' %>

    <%= render(partial: 'form', locals: { f: f }) %>

    <div class="form-buttons">
      <%= f.submit("Create Task") %>
    </div>

  <% end %>
</div>

app/views/tasks/show.html.erb
<%= link_to("Back to List", tasks_path, class: 'back-link') %>

<div class="tasks show">
  <h2>Show task</h2>

  <div class="actions">
    <%= link_to('Edit', edit_task_path(@task)) %>
    <%= link_to('Delete', delete_task_path(@task)) %>
  </div>

  <table summary="Task detail view">
    <tr>
      <th>Name</th>
      <td><%= @task.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @task.position %></td>
    </tr>
    <tr>
      <th>Completed</th>
      <td><%= status_tag(@task.completed?) %></td>
    </tr>
    <tr>
      <th>Description</th>
      <td><%= simple_format(word_wrap(@task.description, line_width: 40)) %></td>
    </tr>
    <tr>
      <th>Category</th>
      <td>
        <%= @task.category&.name || '-' %>
      </td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @task.created_at.to_fs(:long) %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @task.updated_at.to_fs(:long) %></td>
    </tr>
  </table>

</div>